# Generated by Django 4.0.3 on 2022-03-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testProj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postText',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(default='', max_length=72, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
