# Generated by Django 4.0.3 on 2022-03-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testProj', '0002_alter_post_posttext_alter_post_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_reason',
            field=models.CharField(max_length=400),
        ),
    ]
