# Generated by Django 4.0.3 on 2022-04-01 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testProj', '0004_delete_report_delete_usertable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
