# Generated by Django 4.0.3 on 2022-04-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testProj', '0007_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('user_id', models.CharField(max_length=100)),
                ('post_id', models.CharField(default='', max_length=72, primary_key=True, serialize=False)),
                ('postText', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
