# Generated by Django 4.0.3 on 2022-04-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testProj', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reporting_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('reported_id', models.CharField(max_length=36)),
                ('report_reason', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
