# Generated by Django 4.0.3 on 2022-03-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=512)),
                ('display_name', models.CharField(max_length=200)),
                ('user_blurb', models.CharField(max_length=1000, default="")),
            ],
        ),
    ]
