# Generated by Django 4.0.4 on 2022-04-12 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tellmeastory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_username', models.CharField(max_length=400)),
                ('report_reason', models.CharField(max_length=400)),
                ('reporting_username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tellmeastory.user')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.CharField(default='', max_length=72, primary_key=True, serialize=False)),
                ('postText', models.CharField(default='', max_length=200)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tellmeastory.user')),
            ],
        ),
    ]
