# Generated by Django 4.0.3 on 2022-04-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellmeastory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='storyimages')),
                ('image_url', models.TextField()),
                ('node_title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=10000)),
                ('has_image_file', models.BooleanField()),
            ],
        ),
    ]
