# Generated by Django 4.0.4 on 2022-05-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellmeastory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='node_content',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_title',
            field=models.CharField(max_length=200),
        ),
    ]
