# Generated by Django 4.0.3 on 2022-04-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellmeastory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mature',
            field=models.BooleanField(default=False),
        ),
    ]
