# Generated by Django 4.0.3 on 2022-04-13 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tellmeastory', '0002_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='has_image_file',
        ),
    ]
