# Generated by Django 4.0.4 on 2022-04-12 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tellmeastory', '0002_user_email_name_report_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_name',
        ),
    ]
