# Generated by Django 4.0.4 on 2022-05-11 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tellmeastory', '0002_alter_node_node_content_alter_node_node_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reported_id',
        ),
        migrations.AddField(
            model_name='report',
            name='reported_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reported_user', to='tellmeastory.user'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_reporting', to='tellmeastory.user'),
        ),
    ]
