# Generated by Django 4.0.3 on 2022-04-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellmeastory', '0003_user_admin_user_profile_pic_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic.jpg', null=True, upload_to=''),
        ),
    ]
