# Generated by Django 4.0.4 on 2022-04-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellmeastory', '0003_remove_user_email_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='reported_username',
            new_name='reported_posts',
        ),
        migrations.AlterField(
            model_name='report',
            name='report_reason',
            field=models.CharField(max_length=600),
        ),
    ]
