# Generated by Django 4.0.3 on 2022-04-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellmeastory', '0003_remove_node_has_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='has_image_file',
            field=models.BooleanField(default=False),
        ),
    ]
