# Generated by Django 4.0.3 on 2022-04-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellmeastory', '0004_node_has_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='image',
            field=models.ImageField(upload_to='../media/storyimages'),
        ),
    ]
