# Generated by Django 4.0.3 on 2022-04-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellmeastory', '0004_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='audio_exists',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='node',
            name='node_audio',
            field=models.FileField(default=None, upload_to='storyaudio'),
        ),
    ]
