# Generated by Django 4.0.4 on 2022-04-14 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tellmeastory', '0007_ban'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='report_id',
            new_name='reported_username',
        ),
    ]
