# Generated by Django 4.0.3 on 2022-05-09 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tellmeastory', '0007_account_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=1)),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tellmeastory.node')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tellmeastory.user')),
            ],
        ),
    ]
