# Generated by Django 4.0.4 on 2022-04-14 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tellmeastory', '0008_rename_report_id_report_reported_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reported_username',
        ),
        migrations.AddField(
            model_name='report',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tellmeastory.post'),
        ),
    ]
