# Generated by Django 4.0.4 on 2022-05-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellmeastory', '0008_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='ojjosh55@gmail.com', max_length=254),
        ),
    ]
