# Generated by Django 4.0.4 on 2022-05-12 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managetags', '0001_initial'),
        ('tellmeastory', '0009_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannedUser', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reporting_username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tellmeastory.user')),
                ('reported_id', models.CharField(max_length=400)),
                ('report_reason', models.CharField(max_length=600)),
                ('id_for_report', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
        migrations.RemoveField(
            model_name='node',
            name='audio_exists',
        ),
        migrations.RemoveField(
            model_name='node',
            name='node_audio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='node',
            name='latitude',
            field=models.DecimalField(decimal_places=21, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='longitude',
            field=models.DecimalField(decimal_places=21, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='post_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='other_tags',
            field=models.ManyToManyField(blank=True, to='managetags.tag'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='report',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tellmeastory.node'),
        ),
    ]
