# Generated by Django 4.0.4 on 2022-04-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellmeastory', '0009_remove_report_reported_username_report_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
