# Generated by Django 4.0.4 on 2022-04-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellmeastory', '0011_remove_report_id_alter_report_reporting_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_id',
            field=models.CharField(max_length=100),
        ),
    ]
