# Generated by Django 4.0.4 on 2022-04-14 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tellmeastory', '0002_user_mature'),
        ('tellmeastory', '0013_remove_report_report_id_report_id_for_report'),
    ]

    operations = [
    ]
