# Generated by Django 4.0.4 on 2022-04-26 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tellmeastory', '0014_merge_20220414_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tellmeastory.node'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
