# Generated by Django 4.0.4 on 2022-04-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellmeastory', '0016_alter_node_other_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='post_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
