# Generated by Django 4.0.3 on 2022-03-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=255)),
                ('countID', models.IntegerField(default=-1)),
                ('usage_count', models.IntegerField(default=0)),
                ('language', models.CharField(max_length=255)),
            ],
        ),
    ]
